export const SET_EVENTS_SET_SYMBOL = Symbol('SET_EVENTS_SET_SYMBOL');

export const INCREMENT_EVENTS_SET_SYMBOL = Symbol(
  'INCREMENT_EVENTS_SET_SYMBOL'
);

export const DECREMENT_EVENTS_SET_SYMBOL = Symbol(
  'DECREMENT_EVENTS_SET_SYMBOL'
);

export const LISTENER_TYPE_SYMBOL = Symbol('LISTENER_TYPE_SYMBOL');
